language: python
python:
  - "2.7"

notifications:
  email: false

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
  # - conda update --yes --no-deps conda
  # OK, this used to *fix* the build, but now it *breaks* the build.
  # If you're reading this, good luck out there. I'm not sure what to tell you.
  - conda update --yes conda
  # Append the conda-forge channel, instead of adding it. See:
  # https://github.com/conda-forge/conda-forge.github.io/issues/232)
  - conda config --append channels conda-forge
  - conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - |
      if [ $BUILD_DOCS == true ]; then
        conda install -n testenv --yes ipython=5.1.0 sphinx=1.4.8 numpydoc=0.6.0 nbconvert=4.2.0
        pip install sphinx_bootstrap_theme==0.4.12
      fi
  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - conda list
  - pip install -r requirements.txt

script: nosetests --with-coverage --cover-package=flask_request_validator --exe ./tests
after_success: coveralls